[package]
name = "update-alternatives"
version = "0.5.0"
authors = ["gregjm@umich.edu", "git@fthomys.me"]

[dependencies]
clap = { version = "4.5.49", features = ["cargo"] }
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
nix = { version = "0.30.1", features = ["user"] }
